import type { Metadata } from "next";

import { Inter } from "next/font/google";

import React from "react";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";


const inter = Inter({ subsets: ["latin"] });

 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type QueryProviderProps = {
  children: React.ReactNode;
};


export default function RootLayout({ children }: QueryProviderProps) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className} >
            {children}
        </body>
      </html>
    </ClerkProvider>

  );
}
  